// flow-typed signature: 8ba94dcb3a90155f183a5ed56d96f25f
// flow-typed version: <<STUB>>/electron-reload_v1.2.5/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-reload'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-reload' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-reload/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-reload/main.js' {
  declare module.exports: $Exports<'electron-reload/main'>;
}
